### ISSUE TITLE
✨ [FEAT] DB 연결 및 CRUD 생성

### ISSUE THREAD

**Issue by silvarge** [NAU-DOU/DOU_Backend#31]
# 🔥[FEAT]: DB 연결 및 CRUD 생성 #30 
---

### 📝 이슈 설명
- DB 연동
- CRUD
---
- 설명을 작성해주세요

### ✅ To-DO List

---
- [x] Room 작성 및 디테일 정비
- [x] Record 작성 및 디테일 정비
- [x] Record 저장 관련 데이터 확인 ㅠㅠ
- [x] Chat 작성 및 디테일 정비
- [x] Swagger Description 수정해서 넣기

### 💡 특이 사항 및 비고 작성란
- Record 부분 다시 보기
---
