### ISSUE TITLE
[Docs] Swagger 설명 추가 및 수정

### ISSUE THREAD

**Issue by silvarge** [NAU-DOU/DOU_Backend#39]
# [Docs]: Swagger 설명 추가 및 수정
---

### 📝 이슈 설명

---
- 설명을 작성해주세요

### ✅ To-DO List

---
#### Swagger에 Security 관련 세팅
- [x] token 인증 기능 추가 (기능만 추가-존재만 하도록)

#### Swagger 설명 추가 - oauth
- [x] 로그인 (kakao, kakao/callback)
- [x] 리프레시 (kakao/refresh)
- [x] 로그아웃 (kakao/logout)

#### Swagger 수정
- [x] 감정 분석 - sentiment // 모델 수정으로 확인 필수
- [x] GPT 응답 프롬프트 - gpt
- [x] 도우와의 대화 관련 - room, record, chat
   - [x] Room
   - [x] Record
   - [x] Chat
- [x] 전반적인 swagger 형태 다시 잡기

### 💡 특이 사항 및 비고 작성란

---
